### ISSUE TITLE
Events in plant detail

### ISSUE THREAD

**Issue by cesarblancg** [MDeLuise/plant-it#1]
### Question

Hi! 
I'm trying out your project and I don't understand the use of the events. 

When you're in plant details,  the button "add event" doesn't do anything or shows anything in the logs. 
When I manually add an event from the main menu, it doesn't appear in the "Events" section in plant details.

**Comment by MDeLuise** [comment]
Hi @cesarblancg !
Thanks for trying the project, hopefully it would be useful to you.

As for now, the project it's still in an "initial" developing stage, no release has been published yet, so some features are missing.
For now, the "plant details" view you mention needs some refinements as you observed: edit of the info, add/view events, etc. it's not possible yet.

However, you can add events in the main view of the app, simply clicking the "plus" button in the center of the bottom bar.
The event will be stored and it will appear in the homepage section and in the events section.
<img src="https://github.com/MDeLuise/plant-it/assets/66636702/6df3ca00-e848-4c4f-8a89-ac4954a216fa" width="250px"/>
This for now is the only way to add events (excluding the usage of the rest api).

Plan is to pack a first release-ready version of the app in a few weeks.

**Comment by cesarblancg** [comment]
Awesome!
