### ISSUE TITLE
Configurable CORS origin through environment variable

### ISSUE THREAD

**Issue by coloursofnoise** [MDeLuise/plant-it#10]
### Avoid duplicated feature requests

- [X] There are no open or closed feature requests that are related to this request

### Description

Currently the backend is hardcoded to only accept requests from `http://localhost:3000` [^1].
This should be made configurable to allow for more flexible setups.

[^1]: https://github.com/MDeLuise/plant-it/blob/9456fb4e2822c4ecafc6b2129e69ed1fc997faa1/backend/src/main/java/com/github/mdeluise/plantit/security/ApplicationSecurityConfig.java#L106

### Solution

Add an environment variable (`BASE_URL` or similar) that is used to set the allowed origin for CORS.
This would mean it could be easily configured for the backend using the docker-compose file.

### What are alternatives?

This problem currently circumvented by the nginx reverse-proxy[^1], which would no longer be required if this were implemented.

[^1]: https://github.com/MDeLuise/plant-it/blob/9456fb4e2822c4ecafc6b2129e69ed1fc997faa1/deployment/default.conf#L15

**Comment by MDeLuise** [comment]
Thanks for the feedback, started working in #11, after the merge this should be possible

**Comment by MDeLuise** [comment]
Hi @coloursofnoise!
In addition to #11, the recent merge of #21 introduces some changes that also should fix this issue.
Please read the updated [docker deployment](https://github.com/MDeLuise/plant-it?tab=readme-ov-file#setup-with-docker) and the new [dns and cors](https://github.com/MDeLuise/plant-it?tab=readme-ov-file#dns-and-cors) sections of the `README`.

As soon as possible I will push the `0.0.12` docker images for the backend and frontend with those changes.
