### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by nykroy** [MDeLuise/plant-it#117]
### Avoid duplicated feature requests

- [X] There are no open or closed feature requests that are related to this request

### Description

IS a good idea translate app yo another languages.
If you tell me how can i help you, i can translate It to Spanish.

Thank for this really good app

**Comment by MDeLuise** [comment]
Hi @nykroy, thank you for opening this pull request.

Absolutely, internationalization of the app is crucial, and I appreciate your proposal for the Spanish translation.
I believe this feature should be implemented after or during the UI refactoring/restructuring, which is tracked with issue #113. This refactoring is planned to be completed before the first major release of the project.

I'll keep this issue updated with any progress or updates that arise. Thanks again for your contribution!

**Comment by DieterKoblenz** [comment]
> Hi @nykroy, thank you for opening this feature request.
> 
> Absolutely, internationalization of the app is crucial, and I appreciate your proposal for the Spanish translation. I believe this feature should be implemented after or during the UI refactoring/restructuring, which is tracked with issue #113. This refactoring is planned to be completed before the first major release of the project.
> 
> I'll keep this issue updated with any progress or updates that arise. Thanks again for your contribution!

Imho it should be implemented during so that you don't have to do work twice.

**Comment by DieterKoblenz** [comment]
I'd be happy to help translate as soon as I get it up and running.

**Comment by MDeLuise** [comment]
Hey everyone!

The latest version of the app, `0.5.0`, has just been released as part of the project. Now, if you're interested in contributing transactions to enhance the app, you can get started by following the guide provided [here](https://github.com/MDeLuise/plant-it/discussions/148).

Should you encounter any issues or have questions along the way, feel free to reach out to me. Your support and contributions are greatly appreciated, thanks.
