### ISSUE TITLE
Option for maximum width

### ISSUE THREAD

**Issue by filcuk** [MDeLuise/plant-it#118]
### Avoid duplicated feature requests

- [X] There are no open or closed feature requests that are related to this request

### Description

Please consider adding an option for max width on desktop, to make the page more pleasant to use on wide screens.

### Solution

Similar options to what Monica 4.x provides:
![image](https://github.com/MDeLuise/plant-it/assets/1339532/b6fae327-036b-46ea-8758-45ee0edb4555)

**Comment by MDeLuise** [comment]
Hi @filcuk, thank you for opening this feature request.

I have plans to redesign/restructure the frontend before the first major release of the project (feature tracked in https://github.com/MDeLuise/plant-it/issues/113).
However, in the meantime, I believe adding an option for max width on desktop screens is a great idea.
I'll go ahead and implement it. Thanks for your suggestion!

**Comment by MDeLuise** [comment]
I'm closing the issue since on new version of the app (`0.6.0`) the maximum width is set.
