### ISSUE TITLE
Backend error when trying to add plant

### ISSUE THREAD

**Issue by Sennevds** [MDeLuise/plant-it#133]
### Avoid duplicated bug reports

- [X] I've found a bug and checked that there are no open or closed bug report related to this.

### Description

When trying to add a new plant via the search option I get following error as response:
`{
    "statusCode": 500,
    "errorCode": "INTERNAL_SERVER_ERROR",
    "message": "Could not commit JPA transaction"
}`
In the backend logs nothing is shown

**Comment by MDeLuise** [comment]
Hi @Sennevds, thanks for opening the issue!
I just pushed an hotfix version of the backend service, the `0.4.1`, could you please try if the problem is fixed in that version?

**Comment by Sennevds** [comment]
Works thanks for the fast response!

**Comment by MDeLuise** [comment]
Thank you for reporting this issue and using the project!

**Comment by nykroy** [comment]
I have the jpa transaction error. And the app said i have 0.3 version after Re-pull image and redeploy :s
![Screenshot_20240226-190545](https://github.com/MDeLuise/plant-it/assets/7745881/57ec49e2-f3ce-464b-9b83-2f5f2364b1da)
![Screenshot_20240226-190318](https://github.com/MDeLuise/plant-it/assets/7745881/3e3d19e1-44a4-4c9d-b531-a64048613439)

**Comment by nykroy** [comment]
With image: msdeluise/plant-it-backend:0.4.1 i have the same problem

**Comment by MDeLuise** [comment]
Hi @nykroy, thanks for bringing this issue to my attention.
Could you please let me know when you encountered the issue?

I apologize for the inconvenience caused. It appears that the version number in the releases of the app was not updated correctly, leading to the display of `0.3.0` instead of `0.4.1`. I will push a small fix for this tomorrow morning.

Thank you for your patience and understanding.

**Comment by nykroy** [comment]
thank you for your super usefull app 😃!

I encountered when i do a re-pull image and redeploy on my stack on portainer

**Comment by MDeLuise** [comment]
Thank you for using the project! 😁
Unfortunately as you noticed, some little bugs were introduced in the last release but I'm working on fixing them.

I just pushed a `0.4.2` version of the `backend`, now the app should show the right version.
Could you please download this new version and let me know if your problem still persist?

**Comment by nykroy** [comment]
Now i have the correct version. I can add reminder but i can activate reminders 
![Screenshot_20240226-215752](https://github.com/MDeLuise/plant-it/assets/7745881/a6c427f1-caed-4397-b838-cef452e12d9a)

**Comment by MDeLuise** [comment]
> Ok the notification problem IS solved configuring email address for the user. 🤣. All problems are solved with 0.4.2 and email config

Great that was that! 😁
Does everything appear to work correctly now?

**Comment by MDeLuise** [comment]
Great that was that! 😁
If you incurred in any other issue you're welcome to open a bug

Happy planting 🪴
