### ISSUE TITLE
Select Thumbnail for plant instead of 

### ISSUE THREAD

**Issue by apachano** [MDeLuise/plant-it#145]
### Avoid duplicated feature requests

- [X] There are no open or closed feature requests that are related to this request

### Description

I would like to select one of the photos of my plant itself for the thumbnail instead of the species thumbnail so it's easier to identify my specific plant in the list of plants.

**Comment by MDeLuise** [comment]
Hi @apachano, thanks for opening the feature request.

For the project releases up to `0.4.3`, you can do that following these steps:
1. Select the plant you want to change the thumbnail
2. Upload an image you want to use as thumbnail
3. Open the uploaded image and click on "Set as Plant Avatar" button

While for the project release `0.5.0`, you can do that following these steps:
1. Select the plant you want to change the thumbnail
2. Upload an image you want to use as thumbnail
3. Open the uploaded image and click on floating button representing an avatar
