### ISSUE TITLE
Last versión 0.5 IS not present on portainer stack 

### ISSUE THREAD

**Issue by nykroy** [MDeLuise/plant-it#149]
### Avoid duplicated bug reports

- [X] I've found a bug and checked that there are no open or closed bug report related to this.

### Description

I use this stack but i still on 0.4.3: 

`version: "3"
name: plant-it
services:
    backend:
        image: msdeluise/plant-it-backend:latest
        environment:
         - MYSQL_HOST=db
         - MYSQL_PORT=3306
         - MYSQL_USERNAME=root
         - MYSQL_PSW=xxxx
         - MYSQL_ROOT_PASSWORD=xxxx
         - MYSQL_DATABASE=bootdb
         - JWT_SECRET=putTheSecretHere
         - JWT_EXP=1
         - USERS_LIMIT=-1
         - UPLOAD_DIR=/upload-dir
         - API_PORT=8080
         - CACHE_TTL=86400
         - CACHE_HOST=cache
         - CACHE_PORT=6379
         - TREFLE_KEY=NeZXoHZk4hZpjZJm1URaPRNyIlio_QIwdn_dS-O1WqA
         - ALLOWED_ORIGINS=*
         - LOG_LEVEL=DEBUG
         - UPDATE_EXISTING=false
         - SMTP_HOST=smtp.gmail.com
         - SMTP_PORT=587
         - SMTP_EMAIL=xxxxxx
         - SMTP_PASSWORD=xxxxx
         - SMTP_AUTH=true
         - SMTP_START_TTL=true
         - CONTACT_MAIL=xxxxxxx
         - REMINDER_NOTIFY_CHECK=0 30 7 * * * 
         - SSL_ENABLED=false
         - CERTIFICATE_PATH=/certificates/

         
        depends_on:
          - db
          - cache
        restart: unless-stopped
        volumes:
          - "/volume2/docker/plant-it/upload-dir:/upload-dir"
          - "/volume2/docker/plant-it/certs:/certificates"
        ports:
          - "8080:8080"

    db:
        image: mysql:8.0
        restart: always
        environment:
         - MYSQL_HOST=db
         - MYSQL_PORT=3306
         - MYSQL_USERNAME=root
         - MYSQL_PSW=xxxx
         - MYSQL_ROOT_PASSWORD=xxx
         - MYSQL_DATABASE=bootdb
         - JWT_SECRET=putTheSecretHere
         - JWT_EXP=1
         - USERS_LIMIT=-1
         - UPLOAD_DIR=/upload-dir
         - API_PORT=8080
         - CACHE_TTL=86400
         - CACHE_HOST=cache
         - CACHE_PORT=6379
         - TREFLE_KEY=
         - ALLOWED_ORIGINS=*
         - LOG_LEVEL=DEBUG
         - UPDATE_EXISTING=false
         - SMTP_HOST=smtp.gmail.com
         - SMTP_PORT=587
         - SMTP_EMAIL=xxxxxxx
         - SMTP_PASSWORD=xxxxxxx
         - SMTP_AUTH=true
         - SMTP_START_TTL=true
         - CONTACT_MAIL=xxxxxx
         - SSL_ENABLED=false
         - CERTIFICATE_PATH=/certificates/
         
        volumes:
          - "/volume2/docker/plant-it/db:/var/lib/mysql"

    cache:
        image: redis:7.2.1
        restart: always

    frontend:
        image: msdeluise/plant-it-frontend:latest
        environment:
         - PORT=3000
         - API_URL=http://192.168.218.10:8080/api
         - WAIT_TIMEOUT=5000
         - CACHE_TTL_DAYS=7
         - PAGE_SIZE=25
         - BROWSER=none
         - SSL_ENABLED=false
         - CERTIFICATE_PATH=/certificates/
        links:
          - backend
        ports:
          - "3000:3000"
        volumes: 
        - "/volume2/docker/plant-it/certs:/certificates"
volumes:
  certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./certificates`

**Comment by nykroy** [comment]
i am sorry bad update from stack for my. Beautifull front-end. Thank you very much for your work!!!!

**Comment by MDeLuise** [comment]
Glad to know that everything works fine, really thanks!
