### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by lockheed** [MDeLuise/plant-it#150]
### Avoid duplicated bug reports

- [X] I've found a bug and checked that there are no open or closed bug report related to this.

### Description

This is how your documentation page looks like:

![image](https://github.com/MDeLuise/plant-it/assets/3472480/806553bf-b6bb-4427-ad88-7b24f479ff1f)

Not very informative.

**Comment by MDeLuise** [comment]
Hi @lockheed, thanks for opening the issue.
The (correctly rendered) documentation is available [here](https://docs.plant-it.org/). I will update the reference in the README of the code, thanks for pointing this out.
