### ISSUE TITLE
Search in trefle blank space error

### ISSUE THREAD

**Issue by cesarblancg** [MDeLuise/plant-it#156]
### Avoid duplicated bug reports

- [X] I've found a bug and checked that there are no open or closed bug report related to this.

### Description

When you write in the search box a whitespace, it returns this error:
![image](https://github.com/MDeLuise/plant-it/assets/29866109/8ced2d04-bf4e-45ad-a73a-20ca8f93758e)

Maybe we can edit the method to check for empty string in the backend side.
https://github.com/MDeLuise/plant-it/blob/6d92a5a4fd581b9e817956b6bd5ce8b26da35500/backend/src/main/java/com/github/mdeluise/plantit/botanicalinfo/BotanicalInfoController.java#L61

**Comment by MDeLuise** [comment]
Hi @cesarblancg, thanks for reporting this!
The fix was merged in https://github.com/MDeLuise/plant-it/pull/161 and will be included in the next release.
