### ISSUE TITLE
GHCR Image

### ISSUE THREAD

**Issue by TMTwatch** [MDeLuise/plant-it#160]
### Avoid duplicated feature requests

- [X] There are no open or closed feature requests that are related to this request

### Description

Would it be possible for you guys to make a GHCR image? Would love to try to get plant-it added to TrueCharts.

**Comment by MDeLuise** [comment]
Hi @TMTwatch, thanks for opening this feature request.

Starting from the latest release, `0.7.2`, the Docker image [is now available also on the GitHub Container Registry](https://github.com/MDeLuise/plant-it/pkgs/container/plant-it-server).
You can find it using `ghcr.io/mdeluise/plant-it-server:latest`
