### ISSUE TITLE
Typo in `TRAFLE_KEY` parameter

### ISSUE THREAD

**Issue by MDeLuise** [MDeLuise/plant-it#17]
### Avoid duplicated bug reports

- [X] I've found a bug and checked that there are no open or closed bug report related to this.

### Description

The `TRAFLE_KEY` parameter should be named `TREFLE_KEY` since the service that use that key is called tr<ins>e</ins>fle and not tr<ins>a</ins>fle.

### Additional info

It has to be chosen if create a breaking change with the previous commits or if achieve this in a backward compatible manner (maybe creating 2 parameters with the same name?)

**Comment by cesarblancg** [comment]
I think that in the early stage it's fine to have breaking changes
