### ISSUE TITLE
Translation not adjusted for reminders

### ISSUE THREAD

**Issue by CodingEmil** [MDeLuise/plant-it#171]
### Avoid duplicated bug reports

- [X] I've found a bug and checked that there are no open or closed bug report related to this.

### Description

The translation is not being used for the dropdown of reminders (screenshot).
![image](https://github.com/MDeLuise/plant-it/assets/116643407/6bc247ea-ab31-4671-b9a8-415267c55d34)

**Comment by MDeLuise** [comment]
Hi @CodingEmil,
Thanks for opening this issue.

The pull request [#123](https://github.com/MDeLuise/plant-it/pull/173) should fix the issue with the translation for the dropdown of reminders.
However, the "reminder snippet" translations (_every X days, from Y_ phrase) like the one shown in my following screenshot still need to be translated.
I will create a new issue and pull request to handle that.

<img width="519" alt="Screenshot 2024-05-25 at 09 25 46" src="https://github.com/MDeLuise/plant-it/assets/66636702/6e1efad3-7e0c-41ab-b463-41c3ca841eb5">
