### ISSUE TITLE
Easy way to change ports, either by .env files or in guide

### ISSUE THREAD

**Issue by Haxzer** [MDeLuise/plant-it#19]
### Avoid duplicated feature requests

- [X] There are no open or closed feature requests that are related to this request

### Description

- Easy way to change active ports, either by .env files or in guide. As I can see, only the nginx proxy is port-interchangeable due to the other links being hardcoded, which I have found doesn't really work for me when both port 8080 and port 3000 is in use by other systems. 

### Solution

Making ports changeable in .env files

**Comment by MDeLuise** [comment]
Hi @Haxzer! Thanks for the feedback.

The recent merge of #21 introduces some changes that also should fix this issue.
Please read the updated [docker deployment](https://github.com/MDeLuise/plant-it?tab=readme-ov-file#setup-with-docker) and the new [change port binding](https://github.com/MDeLuise/plant-it?tab=readme-ov-file#change-port-binding) sections of the `README`.

As soon as possible I will push the `0.0.12` docker images for the backend and frontend with those changes.
