### ISSUE TITLE
Wrong language in Android app

### ISSUE THREAD

**Issue by fsmeets84** [MDeLuise/plant-it#216]
### Avoid duplicated bug reports

- [X] I've found a bug and checked that there are no open or closed bug report related to this.

### Description

I've installed Plant-it on my server and installed the Android app. Everything works fine.
However, when I open the Android app, the default language is Danish, although I'm Dutch.
And I don't see any option to change the language.

When I go directly to the front-end in a webbrowser it shows in English fine.

**Comment by MDeLuise** [comment]
Hi @fsmeets84, thanks for opening the issue!

I'll need to investigate the problem you encountered further. In the meantime, I've added the functionality to change the app language directly within the app. This feature will be included in the upcoming release.
