### ISSUE TITLE
Do you plan to add Gotify notification?

### ISSUE THREAD

**Issue by John710** [MDeLuise/plant-it#258]
### Avoid duplicated feature requests

- [X] There are no open or closed feature requests that are related to this request

### Description

Hello!

I and many people I know use [Gotify](https://gotify.net) for notifications. Did you planning to add this functionality?

**Comment by MDeLuise** [comment]
Hi @John710,
This task has been completed and will be implemented in the next project release.
Thank you for your contribution!
