### ISSUE TITLE
Valid Email Regex should accept all TLDs

### ISSUE THREAD

**Issue by RamonAbudAlcala** [MDeLuise/plant-it#274]
### Avoid duplicated bug reports

- [X] I've found a bug and checked that there are no open or closed bug report related to this.

### Description

I just discovered that the regex to check for valid emails only accepts TLDs for up to 4 characters long.

These days there are TLDs of [all sorts of sizes](https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains). I have not checked for which one is the longest but, for example: .photography or .green are more than 4 characters long. 

I'd recommend to allow for any size of tld, as this also allows for the TLD .local

I have a purely local email server, with a custom TLD with more than 4 characters, used to handle home server and home user notifications. That is how I came across this issue.

This is the file
https://github.com/MDeLuise/plant-it/blob/276077966009381ae22fa62f6cb9c4d75f1b9360/frontend/lib/signup.dart#L77

I suggest to replace line 77 with the one below, although other solutions might exist.
`      r'^[\w-\.]+@([\w-]+\.)+[\w-]{2,}$',`

### Local environment

I am running the latest docker version.

I was testing it with the default environment variables found on the docs.

**Comment by RamonAbudAlcala** [comment]
Hi @MDeLuise ! Thanks for this. I was just trying to deploy again today and it seems that I still have the same problem.

I found another place where the regex appears. Line 41 of this file.
[frontend/lib/more/edit_profile.dart](https://github.com/MDeLuise/plant-it/blob/7db6d4f02f29fa5041e92bc56a3f9df6919eb303/frontend/lib/more/edit_profile.dart#L41)

I have the latest version of the app (on Fdroid) and the latest version of the docker container.

**Comment by MDeLuise** [comment]
Hi @RamonAbudAlcala,
Thanks for pointing this out and for identifying the additional instance of the wrong regex! I’m gonna implement a fix for this, and it will be included in the next release.
