### ISSUE TITLE
Streamline plant details screen

### ISSUE THREAD

**Issue by igorsantos07** [MDeLuise/plant-it#285]
### Avoid duplicated feature requests

- [X] There are no open or closed feature requests that are related to this request

### Description

I would concur that people usually open the plant details to see tasks and journal information, instead of checking how many photos, events and other summary information (which are the details shown above the fold).

Given that assumption, I would suggest moving Event Stats and Reminders up, and place stuff like avatar setting, seller, price and general stats in a new tab (maybe called "Details"?)

Another approach to this would be to run a small pool with the current users and check what they mostly look for when opening that screen. I would still bet it's not to look for the amount of photos hahah

**Comment by MDeLuise** [comment]
Hi @igorsantos07,

This task has been completed and it's implemented in the last project release (`0.9.0`).

Thank you for your contribution!
If you have any further questions or updates regarding this task, feel free to leave a comment below.
