### ISSUE TITLE
FEAT - Support setting "from" field on SMTP emails

### ISSUE THREAD

**Issue by luehm** [MDeLuise/plant-it#289]
### Avoid duplicated feature requests

- [X] There are no open or closed feature requests that are related to this request

### Description

Emails sent during user registration have an arbitrary FROM address, which some email servers (mailcow) reject as the SMTP username does not match the message ENVELOPE from address.

Disabling sender checks may allow a compromised service account to be abused / impersonate email addresses.

Propose setting the `message.setFrom` Spring variable on email send.

![CleanShot_2024-08-20_13 41 58@2x](https://github.com/user-attachments/assets/4409def8-f94d-48c3-b752-fd0aec3169f2)

**Comment by MDeLuise** [comment]
Hi @luehm
This task has been completed and will be implemented in the next project release.
Thank you for your contribution!

If any problem about this occurs, feel free to leave a comment.
