### ISSUE TITLE
Backend port binding

### ISSUE THREAD

**Issue by nietdev** [MDeLuise/plant-it#313]
### Avoid duplicated bug reports

- [X] I've found a bug and checked that there are no open or closed bug report related to this.

### Description

Hi Max, first of all many thanks for the effort spent on this project.
I'm trying to install plant-it and following the instructions seems to me that the backend is binding on port 8199 instead of 8080 

### Local environment

latest (27.09.2024)

**Comment by nietdev** [comment]
Hi @mdeluise, thanks so much for your feedback; no issue at all, I just
suggest to align the documentation with the default settings.
Thanks again for your effort!


Cheers
Nietdev

Il giorno mer 2 ott 2024 alle 16:52 MDeLuise ***@***.***> ha
scritto:

**Comment by MDeLuise** [comment]
I just want to make sure I fully understand your suggestion.
From my perspective, the documentation seems to be aligned with this. In the section [Change Ports Binding](https://docs.plant-it.org/0.8.0/server-installation/#change-ports-binding), it mentions:

> *If you don't want to use the default port 8080, you can do the following: change the port binding in the docker-compose.yml file, e.g. 9090:8080 to set up the port 9090 for the backend service.*

The documentation also provides a [docker-compose example for changing the ports](https://docs.plant-it.org/0.8.0/server-installation/#complete-example).

Do you have any suggestions on how we can further improve this?

Thanks again for your feedback!

**Comment by nietdev** [comment]
Sorry, just realized that I was not clear enough.
From the docs:
name: plant-it
services:
  server:
    image: msdeluise/plant-it-server:latest
    env_file: server.env
    depends_on:
      - db
      - cache
    restart: unless-stopped
    volumes:
      - "./upload-dir:/upload-dir"
      - "./certs:/certificates"
    ports:
      - "8089:8080"
      - "3009:3000"

Instead i have to use 

    ports:
      - "8080:**8199**"
      - "3009:3000"

because the api backend by default is now listening on 8199

Hope this clarified the issue I've opened.
