### ISSUE TITLE
Build backend

### ISSUE THREAD

**Issue by cesarblancg** [MDeLuise/plant-it#4]
### Question

Hi! When I tried to build the backend using ./mvnw spring-boot:run, it showed the following error: maven-wrapper.properties no such file or directory. Maybe you should include the folder in the git repository? I have never used Maven before.

**Comment by MDeLuise** [comment]
Hi!
#5 should fix this, thanks for the observation.
After the merge it will be possible to build and run the backend with the provided maven wrapper, for example:
* `./mvnw spring-boot:run` - connect to a running mysql instance
* `./mvnw spring-boot:run -Dspring-boot.run.profiles=dev` - use embedded h2 database, useful for debugging or developing

I'll also add a section in the main README reporting the `dev` profile simplified deployment for debugging/developing.
