### ISSUE TITLE
Possibility to change thumbnail picture when plant added from search feature.

### ISSUE THREAD

**Issue by tiritibambix** [MDeLuise/plant-it#61]
### Avoid duplicated feature requests

- [X] There are no open or closed feature requests that are related to this request

### Description

When I add a plant I found using the search feature, I can't edit the thumbnail picture.

It is possible when the plant is added as "custom" though.

### Solution

Would be nice to use the search feature to use as a template and then edit the info including thumbnail.

### Additional context

From search function, maybe like in the "custom" window and as in this example :

[![plantit.jpg](https://i.postimg.cc/05FdgJw0/plantit.jpg)](https://postimg.cc/F1bJ3zGY)

**Comment by MDeLuise** [comment]
Thanks for the feedback
Recently I introduced the possibility of changing the plant's avatar, but you're right, right now there is no possibility of changing the thumbnail of a species (unless it's a custom one).
I think it's a good idea, it could be added directly in the "scientific classification" section of one plant of the species, and/or in the "add plant" section (as you pointed out, similar to what is done now for the custom species).

**Comment by MDeLuise** [comment]
Hi @tiritibambix,
After the merge of #65 now it's possible to change the thumbnail of a species provided by Trefle.
When you edit a Trefle species, a new (custom) species is created, and all plants associated with the first one are linked to the second one. So after that you will see two species: the "default" provided by Trefle and the one "created" by you. 

The feature is available in the new `0.1.0` docker images of the system (please see the [release note](https://github.com/MDeLuise/plant-it/releases/tag/0.1.0) for the breaking changes before update).

If any problem occurs, please you're welcome to open a bug issue.
Thanks for the feedback!

**Comment by tiritibambix** [comment]
Hello. I wanted to try this new feature, but when adding a new plant, I get the error `Could not commit JPA transaction`

I couldn't see something related in the logs. Any idea ?

**Comment by MDeLuise** [comment]
Hi!
As for now, you have to search the related species from the "search" section, then open the species, and finally click on the "edit" button at the top right.

For example, let's say that you want to change the thumbnail of the _Sedum spectabile_:
1. Open the species:
    <img src="https://github.com/MDeLuise/plant-it/assets/66636702/13ebf9f2-2236-452a-a67a-2c1a72e070ea" width="30%"/>
1. Click on the edit button in the top right:
    <img src="https://github.com/MDeLuise/plant-it/assets/66636702/17986493-4059-4fe8-9839-4db5e03c61eb" width="30%"/>

I know it's not so user friendly right now. Maybe I can add a button in the plants that leads directly to the relative species, where you can edit it.

**Comment by tiritibambix** [comment]
Ah yes, I didn't understand it has to be done before adding it to my collection.

Thank you for the explanation :)

**Comment by MDeLuise** [comment]
>  but it looks like I can't change the thumbnail (avatar ?) anymore once I've added a plant to my collection. Is this normal ?

I think it should work without problems, does it give you an error message? What steps did you take?

**Comment by tiritibambix** [comment]
Once I have my plant saved, I go to the home screen, select saved plant, click the edit button, but I only have 3 choices, I can't upload a new image as the thumbnail:

![IMG_20231210_212242](https://github.com/MDeLuise/plant-it/assets/69852851/80476850-2e2f-4789-9949-f8377ebf3573)

There used to be such an option.

**Comment by MDeLuise** [comment]
Ok perfect understood!
In order to select an uploaded image as plant avatar you have to:
1. upload an image of that plant
    <img src="https://github.com/MDeLuise/plant-it/assets/66636702/13c1cd46-e3ba-4187-8278-5dfd5de2a5d6" width="30%" />
1. open the image you want to set as avatar
    <img src="https://github.com/MDeLuise/plant-it/assets/66636702/c9a4e2f8-e7f4-4fca-a966-1953a5dcf78c" width="30%" />
1. click on the "set as plant avatar" button
    <img src="https://github.com/MDeLuise/plant-it/assets/66636702/6f26f791-da0d-455c-949b-6d5d448b9209" width="30%" />

I know even this is not so user friendly, it would be right to have that feature in the menu you opened before. I'll enhance this.
Also, I've started writing more detailed instructions for the app, and once I'm done, I'll be help out for sure.

**Comment by tiritibambix** [comment]
Oh yes, thank you. I guess I could have found that on my own...

Thanks for your help once again :)

**Comment by MDeLuise** [comment]
Glad to hear that it works fine 😁
