### ISSUE TITLE
Retrieving Account Information

### ISSUE THREAD

**Issue by cbarond** [MDeLuise/plant-it#62]
### Question

One of my family members forgot the password for her account. Is there a way to reset the password or find her account info in the database?

**Comment by MDeLuise** [comment]
Hi @cbarond, thanks for opening the question.
Unfortunately right now there is no "simple" way to reset a user's password (I will add this feature).

But you can achive this goal updating the user db entry in the following way:
1. Generate the new password's hash using the bcrypt algorithm (for example using [this site](https://www.javainuse.com/onlineBcrypt)).
1. Update the user's password hash in the db. For example let's say:
* the db container is called `plant-it-db-1`,
* the database name is `bootdb`,
* the database user is `root`,
* the database password is `root`,
* the application username is `max`,
* the new application user password is `test`.
Then you can execute from the host machine's shell the following command: `docker exec -i plant-it-db-1 mysql -u root -proot -Dbootdb <<< "UPDATE application_users SET password = '\$2a\$10\$B1jkTRPnrWwi/T5Rz7BbGeGb3AT4SbVmF0/jUJgArQOHA3Oz3WH9K' WHERE username = 'max';"`

Please remember to escape the `$` character in the command.

**Comment by cbarond** [comment]
That worked! Thank you!
