### ISSUE TITLE
Illegal character in fragment at index 62

### ISSUE THREAD

**Issue by makanimike** [MDeLuise/plant-it#67]
### Avoid duplicated bug reports

- [X] I've found a bug and checked that there are no open or closed bug report related to this.

### Description

I just installed the docker version of the app. After initially running into the missing backend issue because I unnecessarily changed the ports in frontend.env and backend.env .  
  
After fixing that with the help of another thread here (https://github.com/MDeLuise/plant-it/issues/60), it seemed to be up and running.  

I created my user account. And then I got the following error. I get this error message every time I log in. 

`Illegal character in fragment at index 62: https://trefle.io/api/v1/species/search?limit=5&page=1&token=# put you key here, otherwise the "search" feature will include only user generated species&q=*`  
  
I am pretty sure content is not loading that should be there. Probably the database of plants. I can hit the +, but anything I type into a field will be removed as soon as I click outside of the field again.  
If I go to Search (I assume that is normally the database), and start searching, I get the error above again:

![image](https://github.com/MDeLuise/plant-it/assets/88232673/b2d6fd1d-2078-4a24-a003-debf7d8b069f)  
  
Sometimes it will reference index 66.

### Expected behaviour

content to be available, specifically a database of plants. or to at least be able to add my own plants.

### Local environment

docker compose

**Comment by makanimike** [comment]
ok, that was incredibly stupid. RTFM

**Comment by MDeLuise** [comment]
Hi @makanimike, thanks for opening the issue.

From the reported error message, I suspect that in your `backend.env` file there is exactly the following line:
```
TRAFLE_KEY= # put you key here, otherwise the "search" feature will include only user generated species
```

If you don't want to use the trefle service, you can delete that line from the file.
Instead, if you want to use the service, you have to change that line to something similar to
```
TRAFLE_KEY=xyzk...
```
where `xyzk...` is the api key obtained from the [trefle](https://trefle.io/) account.

<hr>

Let me know if removing the `TRAFLE_KEY` line from the file solves the issue.

**Comment by makanimike** [comment]
I got it working after signing up and getting the key :) of course.  
  
  
there is still a tiny piece of constructive feedback we can get from this:  
you have a little typo. it is trefle not trafle.
