### ISSUE TITLE
Cannot connect to backend

### ISSUE THREAD

**Issue by NascarUk** [MDeLuise/plant-it#85]
### Avoid duplicated bug reports

- [X] I've found a bug and checked that there are no open or closed bug report related to this.

### Description

When I run the application on Linux with docker compose and the ports that have been previously discussed I keep getting this error. (This is using both custom docker-compose.yml and the example ones set out in the guide)

### Expected behaviour

Correct connection to backend.

### Steps to reproduce

Add docker-compose.yml , backend.env and frontend.env in your directory
Run sudo docker-compose up -d

### Local environment

Running in docker on linux vm. Other docker compose apps run fine. I have added the log file in which I think the error is occuring!

### Additional info

[_plant-it-backend-1_logs.txt](https://github.com/MDeLuise/plant-it/files/14001297/_plant-it-backend-1_logs.txt)

Please let me know if you need anymore info! I am super excited to get this up and running

**Comment by MDeLuise** [comment]
Hi @NascarUk, thanks for opening the issue!
Can you please provide the content of the files (`docker-compose.yml`, `backend.env`, `frontend.env`) you're using?

**Comment by NascarUk** [comment]
version: "3"
name: plant-it
services:
    backend:
        image: msdeluise/plant-it-backend:latest
        env_file: backend.env
        depends_on:
          - db
          - cache
        restart: unless-stopped
        volumes:
          - "./upload-dir:/upload-dir"
        ports:
          - "5062:8080"

    db:
        image: mysql:8.0
        restart: always
        env_file: backend.env
        volumes:
          - "./db:/var/lib/mysql"

    cache:
        image: redis:7.2.1
        restart: always

    frontend:
        image: msdeluise/plant-it-frontend:latest
        env_file: frontend.env
        links:
          - backend
        ports:
          - "3009:3000"

**Comment by NascarUk** [comment]
`version: "3"
name: plant-it
services:
    backend:
        image: msdeluise/plant-it-backend:latest
        env_file: backend.env
        depends_on:
          - db
          - cache
        restart: unless-stopped
        volumes:
          - "./upload-dir:/upload-dir"
        ports:
          - "5062:8080"

    db:
        image: mysql:8.0
        restart: always
        env_file: backend.env
        volumes:
          - "./db:/var/lib/mysql"

    cache:
        image: redis:7.2.1
        restart: always

    frontend:
        image: msdeluise/plant-it-frontend:latest
        env_file: frontend.env
        links:
          - backend
        ports:
          - "3009:3000"`

**Comment by NascarUk** [comment]
[Backend.env.txt](https://github.com/MDeLuise/plant-it/files/14001728/Backend.env.txt)

**Comment by NascarUk** [comment]
[Frontend.txt](https://github.com/MDeLuise/plant-it/files/14001729/Frontend.txt)
[Backend.txt](https://github.com/MDeLuise/plant-it/files/14001730/Backend.txt)
[docker-compose.txt](https://github.com/MDeLuise/plant-it/files/14001734/docker-compose.txt)

**Comment by MDeLuise** [comment]
I tried to use your configuration and on my side no error, so this is strange.
Before inspect deeply the configuration, could you double check the configuration and try to change the `backend` and `frontend` ports and start the docker compose please?

**Comment by nykroy** [comment]
I has the same error and on my case the problem was i has no permissions on db directory

**Comment by partywagon112** [comment]
I had the same thing, and had to resolve this note from the docs first: https://docs.plant-it.org/installation/configurations/#run-on-a-remote-host
