### ISSUE TITLE
Unsanitized error messages on login/sign-up page

### ISSUE THREAD

**Issue by coloursofnoise** [MDeLuise/plant-it#9]
### Avoid duplicated bug reports

- [X] I've found a bug and checked that there are no open or closed bug report related to this.

### Description

Raw error messages are displayed when:
- No username and/or password is supplied (login and sign-up)
- The provided username is not between 3 and 20 characters long (sign-up)
- The provided password is not between 6 and 40 characters long (sign-up)

### Additional info

Output for a missing password on the login page:
```
Validation failed for argument [0] in public org.springframework.http.ResponseEntity<com.github.mdeluise.plantit.authentication.payload.response.UserInfoResponse> com.github.mdeluise.plantit.authentication.AuthController.authenticateUser(com.github.mdeluise.plantit.authentication.payload.request.LoginRequest): [Field error in object 'loginRequest' on field 'password': rejected value []; codes [NotBlank.loginRequest.password,NotBlank.password,NotBlank.java.lang.String,NotBlank]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [loginRequest.password,password]; arguments []; default message [password]]; default message [must not be blank]] 
```

**Comment by MDeLuise** [comment]
Thanks for the feedback, this should be resolved in #13. I added some check for the `username` and `password` input that prevents the user to send request with those fields too short or too long.
